### ISSUE TITLE
question : spindle count dependent on file length? 

### ISSUE THREAD

**Issue by apoorva6262** [raphaelvallat/yasa#79] opened 2022-06-15 20:02 UTC
Hi @raphaelvallat 

I wanted to know if the spindle count would be affected by the length of the data. For example, if one file is 10s long and the other is 30s, there would be more number of spindles detected in the 30s file , right ? So how do you accommodate for these differences ? Would it be ok to determine spindles in the first 10s of data from both file to be consistent?

**Comment by raphaelvallat** [comment] 2022-06-16 01:18
@apoorva6262 this is correct. If the longer file has more spindles then YASA will detect more spindles. I'm not sure what you mean by "how do you accommodate for these differences", since this is an expected behavior. If desired, you can truncate your data with [mne.Raw.crop](https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.crop). You can also calculate the density which is the number of spindles per minute of a given sleep stage. If you use an hypnogram, and then call sp.summary(grp_stage=True), YASA will automatically calculate the density for you:

```python
sp = spindles_detect(data, sf, hypno, ...)
sp.summary(grp_stage=True, grp_chan=True)
```

**Comment by apoorva6262** [comment] 2022-06-16 02:20
Is spindle density the "frequency" column in the sp.summary data frame ?

**Comment by raphaelvallat** [comment] 2022-06-16 02:21
No there should be a "Density" column, but only if you do pass an hypnogram to the spindles_detect function. Please refer to this notebook: https://github.com/raphaelvallat/yasa/blob/master/notebooks/03_spindles_detection_NREM_only.ipynb

**Comment by apoorva6262** [comment] 2022-06-16 02:30
Hmmm...ok, so my raw file is just the REM epochs. So I dont have different stages and I am only looking at one sleep stage. Is there  a way to get the density column otherwise ?

**Comment by raphaelvallat** [comment] 2022-06-16 02:32
You can create a fake hypnogram, i.e.:

```python
hypno = np.ones(data.size)
sp = yasa.spindles_detect(data, sf, hypno=hypno, include=1)
sp.summary(grp_chan=True, grp_stage=True)
```

**Comment by raphaelvallat** [comment] 2022-07-01 23:30
Closing this, feel free to reopen

**Closed by raphaelvallat** 2022-07-01 23:30 UTC
Labels: question :raising_hand:
